config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :locations
  resources :bookings
  resources :pages

  get 'about' => 'pages#about'

  devise_for :users
  
  root to: 'pages#index'

  
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user, inverse_of: :bookings
    belongs_to :location, inverse_of: :bookings, dependent: :destroy
    validates_presence_of :start, :ends
    validate :no_past_booking
    validate :overlaps
    validate :end_date_after_start_date

    #bookings cannot be in the past for the start and end time
    def no_past_booking
        if start && (start < Time.current )
            errors.add(:Start, "La réservation ne peut pas se faire dans le passé")
    
        end
    end

    #Twice bookings impossible
    def overlaps
        bookings = Booking.where(location_id: id)
        bookings.each do |booking|
            if start < booking.ends && booking.start < ends
                errors.add(:overlaps, 'Déjà réservé à cette date')
            end
        end
    end
   

    private

    # End date must be after start date
    def end_date_after_start_date
        return if ends.blank? || start.blank?

         if ends < start
            errors.add(:ends, "must be after the start date")
        end
    end
     
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include BookingsHelper
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  
  # GET /bookings or /bookings.json
  def index
    @user = current_user
    @bookings = Booking.all.order('created_at DESC')
    @bookings = @user.bookings
    @todays = Booking.where("created_at >= ?", Time.zone.now.beginning_of_day).order("created_at DESC")
    @locations = Location.all
  end
 
  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @locations = Location.all
    @categories = Categorie.all
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "La réservation a été effectuée avec succés"}
        format.json { render :show, status: :created, location: @booking } 
    else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "La réservation a été mise à jour avec succés." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end
        

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "La réservation est annulée"}
      format.json { head :no_content }
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end
  
    # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:start, :ends, :user_id, :location_id)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper

      #Only correct user can perform edit/update/destroy
  def correct_user
    @booking = Booking.find(params[:id])
    unless current_user == @booking.user
      redirect_to(@booking, notice: "Vous ne pouvez pas effectuer cette action")
    end
  end

end

app/views/bookings/_form.html.erb
<%= form_for @booking do |f| %>
<br/>

  <div class="field form-group">
    <%= f.label :catégorie_id %><br/>
    <%= f.collection_select :categorie_id, Categorie.order(:name), :id, :name, include_blank: true %>
  </div>
  <br/>

  <div class="field form-group">
    <%= f.label :location_id %><br/>
    <%= f.grouped_collection_select :location_id, Categorie.order(:name), :locations, :name, :id, :name, include_blank: true %>
  </div>
  <br/>

  <div class="field form-group">
    <%= f.label :start %><br/>
    <%= f.datetime_select :start %>
  </div>
  <br/>

  <div class="field form-group">
    <%= f.label :ends %><br/>
    <%= f.datetime_select :ends %>
  </div>
  <br/>

  <div class="actions">
    <%= f.submit "Réserver", :class => 'btnbis' %>
  </div>
<% end %>


            

app/views/bookings/edit.html.erb
<br/>
<div class="row">
  <div class=" col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
    <div class="card text-center">
      <div class="card-header">Modifier la réservation</div>
        <div class="card-body">
          <br/>
            <%= render 'form', booking: @booking %>
        <br/>
            <%= link_to 'Voir la réservation', @booking, class:"links" %> |
            <%= link_to 'Toutes mes réservations', bookings_path, class:"links" %>
        </div>
    </div>
  </div>
</div>
      

app/views/bookings/index.html.erb
<br/>
<% if user_signed_in? %>
<div class="row">
  <div class="col-sm-10 mx-auto">
    <div class="card text-center">
      <div class="card-header text-center">Toutes mes réservations</div>
        <ul class="list-group list-group-flush">
        <% @bookings.each do |booking| %>
          <li class="list-group-item"><strong>Location :</strong> <%= booking.location.name %> | <strong>Start :</strong> <%= booking.start %> | 
          <strong>End :</strong> <%= booking.ends %> | <strong>User :</strong> <%= booking.user.email %> 
          | <br/>
              <%= link_to 'Show', booking, class:"links" %> | 
              <%= link_to 'Edit', edit_booking_path(booking), class:"links" %> | 
              <%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'En êtes-vous sûrs ??' }, class:"links" %></li>
        <% end %>
        </ul>
    </div>
  </div>
</div>

<br/>
<br/>

<div class="row">
  <div class="col-sm-10 mx-auto">
    <div class="card text-center">
      <div class="card-header text-center">Réservations du jour</div>
        <ul class="list-group list-group-flush">
        <% @todays.each do |booking| %>
          <li class="list-group-item"><strong>Location :</strong> <%= booking.location.name %> | <strong>Start :</strong> <%= booking.start %> | 
          <strong>End :</strong> <%= booking.ends %> | <strong>User :</strong> <%= booking.user.email %> 
          | <br/>
            <% if @user.bookings == current_user %>
              <%= link_to 'Show', booking, class:"links" %> | 
              <%= link_to 'Edit', edit_booking_path(booking), class:"links" %> | 
              <%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'En êtes-vous sûrs ??' }, class:"links" %></li>
            <% else %>
              <p></p>
            <% end %>
          <% end %>
        </ul>
    </div>
  </div>
</div>

<br>
<div class="text-center">
  <%= link_to 'Nouvelle réservation', new_booking_path, class:"links" %><br/><br/>
  <%= link_to 'Accueil', root_path, class:"links" %>
</div>


<% else %>
<br/>
<div class="row">
  <div class="col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
    <div class="card text-center">
      <div class="card-header">Vous avez besoin d'être connecté pour voir vos réservations!</div>
        <div class="card-body">
          <%= link_to 'Se connecter', new_user_session_path %>
        </div>
    </div>
  </div>
</div>
<% end %>

app/views/bookings/new.html.erb
<br/>
<% if user_signed_in? %>
<br/>
<div class="row">
  <div class=" col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
    <div class="card text-center">
      <div class="card-header">Nouvelle réservation</div>
        <div class="card-body">
          <h5 class="card-title"></h5>

            <%= render 'form', booking: @booking %>
            <br/>
            <%= link_to 'Toutes mes réservations', bookings_path, class:"links" %>
        </div>
    </div>
  </div>
</div>
<br/>
 
<% else %>
<br/>
  <div class="row">
    <div class="col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
      <div class="card text-center">
        <div class="card-header">Vous avez besoin d'être connecté pour voir vos réservations!</div>
          <div class="card-body">
            <%= link_to 'Se connecter', new_user_session_path, class:"links" %>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/show.html.erb
<br/>
<div class="row">
  <div class=" col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
    <div class="card text-center">
      <div class="card-header">Informations sur la réservation</div>
        <div class="card-body">
          <br/>
          <p>
            <strong>Location name:</strong>
            <%= @booking.location.name %>
          </p>

          <p>
            <strong>Start:</strong>
            <%= @booking.start %>
          </p>

          <p>
            <strong>End:</strong>
            <%= @booking.ends %>
          </p>

          <p>
            <strong>Location cost:</strong>
            <%= @booking.location.price %>
          </p>
          <br/>

            <%= link_to 'Modifier la réservation', edit_booking_path(@booking), class:"links" %> |
            <%= link_to 'Toutes mes réservations', bookings_path, class:"links" %>
        </div>
    </div>
  </div>
</div>
<br/>

<p id="notice" class="text-center"><strong><%= notice %></strong></p>