config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :locations
  resources :bookings
  resources :pages

  get 'about' => 'pages#about'

  devise_for :users
  
  root to: 'pages#index'

  
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :categorie
    has_many :bookings
    has_one_attached :picture
    has_many :users
    paginates_per 20


    def self.search(search)
        if search 
            where(["name LIKE ?","%#{search}%"])
        else 
            all
        end
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
include LocationsHelper
before_action :set_location, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:show, :index]
before_action :require_login, only: [:edit, :update, :destroy]
before_action :only_admin_for_location_updates, only: [:edit, :update, :destroy]

  

  def index
    @locations = Location.search(params[:search])
    @locations = Location.page(params[:page])
    @categories = Categorie.all
  end
  

  def show
  end

  def new
    @location = Location.new
    @categorie = Categorie.all
  end 


  def create
    @location = Location.new(post_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: "La location a été ajoutée avec succés"}
        format.json { render :show, status: :created, location: @location } 
    else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity}
      end
    end
  end


  def edit
    @location = Location.find(params[:id])
  end


    def update
      respond_to do |format|
        if @location.update(post_params)
          format.html { redirect_to @location, notice: "Location was successfully updated." }
          format.json { render :show, status: :ok, location: @location }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @location.errors, status: :unprocessable_entity }
        end
      end
    end


  def destroy
    @location.destroy
    redirect_to locations_path
  end

  def locationbyuser
    @user = current_user
    @locations = @user.locations
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def post_params
    params.require(:location).permit(:name, :address, :zip_code, :city, :rooms, :superficy, :price, :picture, :description, :categorie_id)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
    private

    def require_login
        unless current_user != nil
            redirect_to new_user_session_path
        end
    end

    def require_permission_edit_location
        unless current_user == @location.user_id
          redirect_to root_path
          #Or do something else here
        end
      end

      def only_admin_for_location_updates
        if !current_user.admin || current_user = nil
            return redirect_to root_path
        end

    end

    
    
end

app/views/locations/_categories_list.html.erb
<div class="container">
<br/>
    <h1 class="text-center">Locations par catégories</h1>
<br/>
    <h4 class="text-center">Retrouvez votre location idéale, ou<br />
    cherchez là selon la catégorie souhaitée.</h4>
<br/>
<div class="row mx-auto">
    <h4 class="text-center">
        <p><%= link_to 'Proposer une nouvelle location', new_location_path, class:"links" %>  
      <%= link_to 'Faire une nouvelle réservation', new_booking_path, class:"links" %>
      
    </h4>
</div>
<br/>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 ">
<% @categories.each do |categorie| %>
  <div class="col mx-auto">
    <div class="card-sl shadow-lg mx-auto text-center">
        <div class="card-image">
            <%= image_tag categorie.picture, class:"img-fluid", width: "auto" if categorie.picture.attached? %>
        </div>
          <%= categorie.name %>
        <div class="col mx-auto text-center">
        <% if current_user && current_user.admin %>
          <%= link_to 'Détails', category_path(categorie), class:"links" %>     
          <%= link_to 'Modifier', edit_category_path(categorie), class:"links" %>     
          <%= link_to 'Supprimer', categorie, method: :delete, data: { confirm: 'En êtes-vous sûrs ?' }, class:"links" %>
        <% else %>
            <%= link_to 'Détails', category_path(categorie), class:"links" %>
        <% end %>
        </div>
    </div>

  </div>

<% end %>
</div> 
</div>
<br />
<br />
<hr>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
    <br/>

        <div class="field form-group">
            <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Nom de location", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :address, autofocus: true, autocomplete: "address", placeholder: "Adresse", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :zip_code, autofocus: true, autocomplete: "zip_code", placeholder: "Code postal", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :city, autofocus: true, autocomplete: "city", placeholder: "Ville", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :rooms, autofocus: true, autocomplete: "rooms", placeholder: "Nombre de pièces", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :superficy, autofocus: true, autocomplete: "superficy", placeholder: "Superficie", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :price, autofocus: true, autocomplete: "price", placeholder: "Prix/nuit", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :description, autofocus: true, autocomplete: "description", placeholder: "Description", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.collection_select :categorie_id, Categorie.order(:name), :id, :name, include_blank: true, class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.file_field :picture %>
        </div>
        <br/>

    
        <div class="actions">
            <%= f.submit "Proposer à la location", :class => 'btnbis' %>
        </div>
        
<% end %>
    
    
                

app/views/locations/_form2.html.erb
<%= form_for @location do |f| %>
    <br/>

        <div class="field form-group">
            <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Nom de location", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :address, autofocus: true, autocomplete: "address", placeholder: "Adresse", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :zip_code, autofocus: true, autocomplete: "zip_code", placeholder: "Code postal", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :city, autofocus: true, autocomplete: "city", placeholder: "Ville", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :rooms, autofocus: true, autocomplete: "rooms", placeholder: "Nombre de pièces", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :superficy, autofocus: true, autocomplete: "superficy", placeholder: "Superficie", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :price, autofocus: true, autocomplete: "price", placeholder: "Prix/nuit", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.text_field :description, autofocus: true, autocomplete: "description", placeholder: "Description", class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.collection_select :categorie_id, Categorie.order(:name), :id, :name, include_blank: true, class:"formControl" %>
        <br/>
        </div>
        <br/>

        <div class="field form-group">
            <%= f.file_field :picture %>
        </div>
        <br/>

    
        <div class="actions">
            <%= f.submit "Mettre à jour", :class => 'btnbis' %>
        </div>
        
<% end %>
    
    
                

app/views/locations/create.html.erb
<h1>Location#create</h1>
<p>Find me in app/views/location/create.html.erb</p>

app/views/locations/destroy.html.erb
<h1>Location#destroy</h1>
<p>Find me in app/views/location/destroy.html.erb</p>

app/views/locations/edit.html.erb
<br/>
<div class="row">
  <div class=" col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
    <div class="card text-center">
      <div class="card-header">Modifier la location</div>
        <div class="card-body">
          <br/>
            <%= render 'form2', location: @location %>
        <br/>
            <%= link_to 'Voir la location', @location, class:"links" %> |
            <%= link_to 'Toutes mes locations', locations_path, class:"links" %>
        </div>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<br/>
  <%= render "locations/categories_list" %>
   <div class="container" style="margin-top:50px;">
   <h1 class="text-center">Toutes les locations</h1>
        <br />
        <div class="row">
          <div class="col text-center mx-auto">
          <%= form_tag locations_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Recherche" %>
          <% end %>
          </div>
        </div>
        <br />
        <br />

    
        <%= paginate @locations %>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
        <% @locations.each do |location| %>
          <div class="col">
            <div class="card-sl shadow-lg">
              <div class="card-image">
                <%= image_tag location.picture, class:"img-fluid", width: "auto" if location.picture.attached? %>
              </div>
              <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                <div class="card-heading">
                  <%= location.name %>
                </div>
                <div class="card-text">
                  Superficy : <%= location.superficy %>
                </div>
                <div class="card-text">
                  Pièces : <%= location.rooms %>
                </div>
                <div class="card-text">
                 Prix : <%= location.price %> €
                </div>

                <div class="col mx-auto text-center">
                  <%= link_to 'Détails', location, class:"links" %>     
                  <%= link_to 'Modifier', edit_location_path(location), class:"links" %>     
                  <%= link_to 'Supprimer', location, method: :delete, data: { confirm: 'En êtes-vous sûrs ?' }, class:"links" %>
                </div>
            </div>
          </div>
       
        <% end %>
      </div> 
    </div>

app/views/locations/new.html.erb
<br/>
<% if user_signed_in? %>
<br/>
<div class="row">
  <div class=" col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
    <div class="card text-center">
      <div class="card-header">Nouvelle location</div>
        <div class="card-body">
          <h5 class="card-title">Enregistrer les informations ci-dessous:</h5>

            <%= render 'form', location: @location %>
            <br/>
            <%= link_to 'Tous mes biens proposés à la location', about_path, class:"links" %>
        </div>
    </div>
  </div>
</div>
<br/>
 
<% else %>
<br/>
  <div class="row">
    <div class="col-sm-8 col-md-6 col-lg-4 mx-auto my-auto">
      <div class="card text-center">
        <div class="card-header">Vous avez besoin d'être connecté pour proposer votre bien à la location</div>
          <div class="card-body">
            <%= link_to 'Se connecter', new_user_session_path, class:"links" %>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/locations/show.html.erb
<div class="container" style="margin-top:50px;">
    <div class="row">
        <div class="col-md-3 mx-auto">
            <div class="card-sl shadow-lg">
                <div class="card-image">
                    <%= image_tag @location.picture, class:"img-fluid", width: "auto" %>
                </div>

                <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                <div class="card-heading">
                    <%= @location.name %>
                </div>
                <div class="card-text">
                    <p><%= @location.description %></p>
                    <p><%= @location.price %> €</p>
                </div>
                <%= link_to "Réserver", new_booking_path(@location.id), class:"nav-link text-center" %>
                
            </div>
        </div>
    </div> 
</div>

app/views/locations/update.html.erb
<h1>Location#update</h1>
<p>Find me in app/views/location/update.html.erb</p>