config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :locations
  resources :bookings
  resources :pages

  get 'about' => 'pages#about'

  devise_for :users
  
  root to: 'pages#index'

  
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_carroussel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("carrou1.jpg", class: "d-block w-100") %>
        <div class="carousel-caption d-none d-md-block">
          <h5 class="animated bounceInRight" style="animation-delay: 1s">OuiDing</h5>
              <p class="animated bounceInLeft" style="animation-delay: 2s">Vous recherchez un site qui centralise des endroits pour réaliser un mariage ou un anniversaire?<br/>
              Vous êtes au bon endroit!</p>
              <p class="animated bounceInRight" style="animation-delay: 3s"><a href="#">Plus d'informations</a></p>
        </div>
    </div>

    <div class="carousel-item">
      <%= image_tag("carrou2.jpg", class: "d-block w-100") %>
        <div class="carousel-caption d-none d-md-block">
          <h4 class="animated zoomIn" style="animation-delay: 1s">Trouvez le lieu de vos envies!</h4>
            <p class="animated fadeInRight" style="animation-delay: 2s">De la Bretagne à la Provence en passant par Monaco, vous trouverez forcèment votre bonheur pour le jour J!</p>
            <p class="animated zoomIn" style="animation-delay: 3s"><a href="#">Plus d'informations</a></p>
        </div>
    </div>

    <div class="carousel-item">
      <%= image_tag("carrou3.jpg", class: "d-block w-100") %>
        <div class="carousel-caption d-none d-md-block">
          <h4 class="animated zoomIn" style="animation-delay: 1s">Tarifs avantageux</h4>
            <p class="animated fadeInLeft" style="animation-delay: 2s">Et les tarifs sont plus qu'abordables</p>
            <p class="animated zoomIn" style="animation-delay: 3s"><a href="#">Plus d'informations</a></p>
        </div>
    </div>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/layouts/_footer.html.erb
<footer id="body">
        <div class="row">
            <div class="col text-center">
                <h1 class=" text-capitalize font-weight-light p-3">OuiDing</h1>
                <h3 class="text-light font-weight-light font-italic mb-3">Tous les lieux liés à l'évènementiel réunis au même endroit</h3>
                <div class="py-2">
                    <a href="#"><i class="fab fa-facebook fa-2x text-primary mx-3"></i></a>
                    <a href="#"><i class="fab fa-google-plus fa-2x text-danger mx-3"></i></a>
                    <a href="#"><i class="fab fa-twitter fa-2x text-info mx-3"></i></a>
                    <a href="#"><i class="fab fa-youtube fa-2x text-danger mx-3"></i></a>
                </div>
                <p class="text-light py-4">&copy;Copyright 2021 - by OuiDing </p>
            </div>
        </div>
</footer>

app/views/layouts/_navbar.html.erb
<div id="body2"">
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">OuiDing</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Toutes les locations', locations_path, class:"nav-link" %>
         
        </li>
        <li class="nav-item">
          <%= link_to 'Faire une réservation', new_booking_path, class:"btn nav-link" %>
        </li>
        <li class="nav-item">
              <%= link_to 'Proposer une location', new_location_path, class:"nav-link" %>
        </li>

        <% if current_user && current_user.admin %>
          <li class="nav-item">
            <%= link_to 'Rajouter une catégorie', new_category_path, class:"nav-link" %>
          </li>
        <% end %>
       
        <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Modifier le profil', edit_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Déconnection', destroy_user_session_path, :method=>'delete', class:"nav-link"%>
            </li>
        <% else %>
            <li class="nav-item">
              <%= link_to 'Inscription', new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Connection', new_user_session_path, class:"nav-link" %>
            </li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>
</div>

app/views/layouts/_thumbnail.html.erb
<div id="res">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
    <% @locations.each do |location| %>
      <div class="col">
        <div class="card h-100 text-center shadow-lg bg-light">      
          <%= image_tag location.picture, width: "auto" if location.picture.attached? %>
            <div class="card-body">
            <h5 class="card-title"><%= location.name %></h5>
              <div class="text">
              <br/>
                <p class="pt-2"><%= location.price %> €</p>
                <p class="pt-2 pb-2">Ville : <%= location.city %></p> 
               
            
                <%= button_to "Plus d'informations", location_path(location), :id => "open-contacts-dialog-btn",
      :class => "btnbis2", :method => :get %>
                     
              </div>
            </div>
        </div>
      </div>
    <% end %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Tokumin:wght@800&family=Poppins:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Unna&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <title>OuiDing</title>

            <%= csrf_meta_tags %>
            <%= csp_meta_tag %>

            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

            
  </head>

  <body>
 
    
  <%= render 'layouts/navbar' %> 

  <%= yield %>


  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
  -->
    
  </body>
</html>

app/views/layouts/brouillon.html.erb
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)






location1 = Location.new(name: "Jardin d'Eden",
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Elegant lieu pour fêter un mariage.", 
categorie: categorie1)
location1.picture.attach(io: File.open("app/assets/images/thum1.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location1.save! 

location2 = Location.new(name: "Le vieux Rocher", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Charmante demeure sur la côte pour évenementiel.", 
categorie: categorie1)
location2.picture.attach(io: File.open("app/assets/images/thum2.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location2.save 

location3 = Location.new(name: "Palais à Monaco",
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Palais pour mariages princiers et royaux.", 
categorie: categorie1)
location3.picture.attach(io: File.open("app/assets/images/thum3.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location3.save 

location4 = Location.new(name: "Vaste chalet breton", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Célèbrez votre union près du littoral breton.", 
categorie: categorie1)
location4.picture.attach(io: File.open("app/assets/images/thum4.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location4.save 

location5 = Location.new(name: "L'hypnose", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Elegant hôtel pour organiser un évènement.", 
categorie: categorie1)
location5.picture.attach(io: File.open("app/assets/images/thum5.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location5.save 

location6 = Location.new(name: "Pomme d'amour", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Superbe demeure pour mariages glamours.", 
categorie: categorie1)
location6.picture.attach(io: File.open("app/assets/images/thum6.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location6.save 

location7 = Location.new(name: "Maisonnet Albâtre", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Mariages buccoliques dans un cadre champêtre.", 
categorie: categorie1)
location7.picture.attach(io: File.open("app/assets/images/thum7.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location7.save 

location8 = Location.new(name: "Château soyeux", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Ne ratez pas cet édifice surprenant.", 
categorie: categorie1)
location8.picture.attach(io: File.open("app/assets/images/thum8.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location8.save 

location9 = Location.new(name: "Villa champêtre", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Une villa d'architecte conçue pour les grandes occasions.", 
categorie: categorie1)
location9.picture.attach(io: File.open("app/assets/images/thum9.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location9.save 

location10 = Location.new(name: "Le monde enchanté", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Coin de paradis pour le jour J.", 
categorie: categorie1)
location10.picture.attach(io: File.open("app/assets/images/thum10.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location10.save 

location11 = Location.new(name: "Le jardin secret", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Sompteux jardin pour mariages royaux.", 
categorie: categorie1)
location11.picture.attach(io: File.open("app/assets/images/thum11.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location11.save 

location12 = Location.new(name: "Songe d'une nuit d'été", 
address: Faker::Address.street_address, 
zip_code: Faker::Address.zip_code, 
city: Faker::Address.city,
rooms: rand(1..10),
superficy: rand(100..350),
price: rand(850..5000),
description: "Palais accueillant mariages et grandes réceptions.", 
categorie: categorie1)
location12.picture.attach(io: File.open("app/assets/images/thum12.jpg"), filename: 'thum.jpg', content_type: 'image/jpeg')
location12.save 


puts "Les salles de réception sont créées !"